name: 'Setup CMake'
description: 'Sets up CMake'
author: 'Your Name <your.email@example.com>'
inputs:
  cmake-version:
    description: 'The CMake version to install'
    required: false
    default: '3.21.3'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
      shell: bash
    - name: Install CMake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v${{ inputs.cmake-version }}/cmake-${{ inputs.cmake-version }}-linux-x86_64.sh
        sudo bash cmake-${{ inputs.cmake-version }}-linux-x86_64.sh --skip-license --prefix=/usr/local
      shell: bash
    - name: Verify CMake installation
      run: cmake --version
      shell: bash
