name: CI

on:
  push:
    /#pull_request:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          apt-get update
          apt-get install -y cmake gcc g++ make

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/Testing/Temporary

      - name: Notify test result
        if: failure()
        run: echo "Unit tests failed. Please check the test results."
