name: CI

on:
  push:
    #pull_request:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          apt-get update
          apt-get install -y cmake gcc g++ make

      #- name: Create build directory
       # run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Build project
        run: cmake --build build --config Debug

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/Testing/Temporary

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: build/Testing/Temporary
          retention-days: 5

      - name: Report test results
        if: always()
        run: |
          mkdir -p test-results
          cp build/Testing/Temporary/LastTest.log test-results/
        continue-on-error: true

      - name: Post test results
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/test-results/LastTest.log'
          require_tests: true
